url_padrao: 'https://www.snd.com.br'
user: 'NATHAN.GOMES@SND.COM.BR'
senha: '123456'
produto1: 'V206HQL'
id1: 'div[data-productid="88482"]'
produto2: 'E970SWNL'
id2: 'div[data-productid="148879"]'
minha conta: 'QA Automação'
busca: 'https://www.snd.com.br/filterSearch?q=V206HQL'
cpf_boleto: '12.580.606/0001-22'
nota_fiscal: '1309418'

