url_padrao: 'https://www.snd.com.br'
user: 'NATHAN.GOMES@SND.COM.BR'
senha: '123456'
produto1: 'LS22F350FHLMZD'
id1: 'div[data-productid="157009"]'
produto2: 'BZ1200-BR'
id2: 'div[data-productid="83101"]'
minha conta: 'QA Automação'
busca: 'https://www.snd.com.br/filterSearch?q=LS22F350FHLMZD'
cpf_boleto: '12.580.606/0001-22'
nota_fiscal: '1309418'
